### ISSUE TITLE
not working on multicraft 2.0

### ISSUE THREAD

**Issue by william1888** [haniokasai/Nukkit-multicraft-config#1]
The server status is not detected as online and the players list is not being cleared when a  player leaves the server

**Comment by haniokasai** [comment]
im using same version,but working.

**Comment by william1888** [comment]
Its picking up some strange letters like "GK" and "DK" and stuff and I think its breaking the lines. 
I rewrote the parse blocks to use the "player has joined" and "player has left" lines instead of the lines that have the ip address and its working fine now!
